name: Feature Request
description: Propose an improvement to PromptImprover.
title: "[Feature]: "
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        Please describe the user problem first, then propose a concrete change.

  - type: checkboxes
    id: preflight
    attributes:
      label: Pre-flight Checklist
      options:
        - label: I searched existing issues and did not find the same request.
          required: true

  - type: textarea
    id: problem_statement
    attributes:
      label: Problem Statement
      description: What user problem are you trying to solve?
      placeholder: Today, users cannot ...
    validations:
      required: true

  - type: textarea
    id: proposal
    attributes:
      label: Proposed Solution
      description: Describe the behavior you want.
      placeholder: Add ...
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: What alternatives did you evaluate?
      placeholder: I also considered ...

  - type: textarea
    id: user_impact
    attributes:
      label: User Impact
      description: Who benefits, and how?
      placeholder: This improves ...
    validations:
      required: true

  - type: textarea
    id: acceptance_criteria
    attributes:
      label: Acceptance Criteria
      description: Define how we know this is complete.
      placeholder: |
        - [ ] Criterion 1
        - [ ] Criterion 2
    validations:
      required: true

  - type: textarea
    id: additional_context
    attributes:
      label: Additional Context
      description: Links, mockups, references, or constraints.

